# # k8s/jfrog-secret.yaml
# apiVersion: v1
# kind: Secret
# metadata:
#   name: jfrog-secret
#   namespace: jarvis
# type: kubernetes.io/dockerconfigjson
# data:
#   # Base64 encoded: {"auths":{"valeodemo.jfrog.io":{"username":"vinay.udaya.shankar@accenture.com","password":"YOUR_TOKEN","auth":"BASE64_OF_USER:PASS"}}}
#   .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJ2YWxlb2RlbW8uamZyb2cuaW8iOiB7CiAgICAgICJ1c2VybmFtZSI6ICJ2aW5heS51ZGF5YS5zaGFua2FyQGFjY2VudHVyZS5jb20iLAogICAgICAicGFzc3dvcmQiOiAiWU9VUl9UT0tFTiIsCiAgICAgICJhdXRoIjogIkJBU0U2NF9PRl9VU0VSOlBBU1MiCiAgICB9CiAgfQp9