# k8s/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: jarvis-secrets
  namespace: jarvis
type: Opaque
stringData:
  # PostgreSQL
  POSTGRES_DB: jarvis_traceability
  POSTGRES_USER: jarvis_user
  POSTGRES_PASSWORD: jarvis_password
  
  # API Connection String
  CONNECTION_STRING: "Host=jarvis-postgres-svc;Database=jarvis_traceability;Username=jarvis_user;Password=jarvis_password"
  
  # Grafana
  GF_SECURITY_ADMIN_USER: admin
  GF_SECURITY_ADMIN_PASSWORD: admin123