# k8s/configmaps/grafana-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: jarvis
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: PostgreSQL
        type: postgres
        url: jarvis-postgres-svc:5432
        database: jarvis_traceability
        user: jarvis_user
        password: jarvis_password
        editable: false
        isDefault: true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboards-config
  namespace: jarvis
data:
  dashboards.yaml: |
    apiVersion: 1
    providers:
      - name: 'default'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        editable: true
        updateIntervalSeconds: 30
        allowUiUpdates: true
        options:
          path: /var/lib/grafana/dashboards
          foldersFromFilesStructure: false