# k8s/ui/ui-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: jarvis-ui-svc
  namespace: jarvis
  labels:
    app: jarvis-ui
    component: frontend
  annotations:
    cloud.google.com/load-balancer-type: "External"
    cloud.google.com/load-balancer-ipv4: "34.163.140.113"
spec:
  type: LoadBalancer
  loadBalancerIP: "34.163.140.113" 
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: jarvis-ui