# k8s/grafana/grafana-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: jarvis-grafana-svc
  namespace: jarvis
  annotations:
    cloud.google.com/load-balancer-ipv4: "34.155.209.143"  # Your reserved IP
spec:
  type: LoadBalancer
  loadBalancerIP: "34.155.209.143"
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: jarvis-grafana