// <auto-generated />
using System;
using Jarvis.Traceability.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Jarvis.Traceability.Api.Migrations.Edge
{
    [DbContext(typeof(EdgeDbContext))]
    [Migration("20260817081123_InitialEdgeDbCreate")]
    partial class InitialEdgeDbCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Jarvis.Traceability.Api.Models.ProcessFlow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FlowCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SyncStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("edge_process_flows", (string)null);
                });

            modelBuilder.Entity("Jarvis.Traceability.Api.Models.ProcessOperation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("OperationCode")
                        .HasColumnType("integer");

                    b.Property<string>("OperationName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("StepId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StepId");

                    b.ToTable("edge_process_operations", (string)null);
                });

            modelBuilder.Entity("Jarvis.Traceability.Api.Models.ProcessResultDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsMandatory")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("Lsl")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Nominal")
                        .HasColumnType("numeric");

                    b.Property<Guid>("OperationId")
                        .HasColumnType("uuid");

                    b.Property<int>("ResultCode")
                        .HasColumnType("integer");

                    b.Property<string>("ResultName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("ResultType")
                        .HasColumnType("integer");

                    b.Property<string>("Uom")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal?>("Usl")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("OperationId");

                    b.ToTable("edge_process_result_definitions", (string)null);
                });

            modelBuilder.Entity("Jarvis.Traceability.Api.Models.ProcessResultRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("CycleTime")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("DeviceTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FailureCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("MachineTime")
                        .HasColumnType("numeric");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("StationCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("StationMode")
                        .HasColumnType("integer");

                    b.Property<int>("StepCode")
                        .HasColumnType("integer");

                    b.Property<int>("StepResult")
                        .HasColumnType("integer");

                    b.Property<string>("StorageMode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("WpcNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("process_result_records", (string)null);
                });

            modelBuilder.Entity("Jarvis.Traceability.Api.Models.ProcessResultValue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("OperationCode")
                        .HasColumnType("integer");

                    b.Property<Guid>("RecordId")
                        .HasColumnType("uuid");

                    b.Property<int>("ResultCode")
                        .HasColumnType("integer");

                    b.Property<string>("ValueFileRef")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("ValueNumeric")
                        .HasColumnType("numeric");

                    b.Property<string>("ValueText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RecordId");

                    b.ToTable("process_result_values", (string)null);
                });

            modelBuilder.Entity("Jarvis.Traceability.Api.Models.ProcessStep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FlowId")
                        .HasColumnType("uuid");

                    b.Property<int>("StepCode")
                        .HasColumnType("integer");

                    b.Property<string>("StepName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("StepOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FlowId");

                    b.ToTable("edge_process_steps", (string)null);
                });

            modelBuilder.Entity("Jarvis.Traceability.Api.Models.RecordingAuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ClientIp")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("LatencyMs")
                        .HasColumnType("double precision");

                    b.Property<string>("RawPayload")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("StorageMode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("recording_audit_logs", (string)null);
                });

            modelBuilder.Entity("Jarvis.Traceability.Api.Models.StationStepMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LineCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("StationCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("StepId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StepId");

                    b.ToTable("edge_station_step_mappings", (string)null);
                });

            modelBuilder.Entity("Jarvis.Traceability.Api.Models.ProcessOperation", b =>
                {
                    b.HasOne("Jarvis.Traceability.Api.Models.ProcessStep", "Step")
                        .WithMany("Operations")
                        .HasForeignKey("StepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Step");
                });

            modelBuilder.Entity("Jarvis.Traceability.Api.Models.ProcessResultDefinition", b =>
                {
                    b.HasOne("Jarvis.Traceability.Api.Models.ProcessOperation", "Operation")
                        .WithMany("ResultDefinitions")
                        .HasForeignKey("OperationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Operation");
                });

            modelBuilder.Entity("Jarvis.Traceability.Api.Models.ProcessResultValue", b =>
                {
                    b.HasOne("Jarvis.Traceability.Api.Models.ProcessResultRecord", "Record")
                        .WithMany("Values")
                        .HasForeignKey("RecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Record");
                });

            modelBuilder.Entity("Jarvis.Traceability.Api.Models.ProcessStep", b =>
                {
                    b.HasOne("Jarvis.Traceability.Api.Models.ProcessFlow", "Flow")
                        .WithMany("Steps")
                        .HasForeignKey("FlowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Flow");
                });

            modelBuilder.Entity("Jarvis.Traceability.Api.Models.StationStepMapping", b =>
                {
                    b.HasOne("Jarvis.Traceability.Api.Models.ProcessStep", "Step")
                        .WithMany()
                        .HasForeignKey("StepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Step");
                });

            modelBuilder.Entity("Jarvis.Traceability.Api.Models.ProcessFlow", b =>
                {
                    b.Navigation("Steps");
                });

            modelBuilder.Entity("Jarvis.Traceability.Api.Models.ProcessOperation", b =>
                {
                    b.Navigation("ResultDefinitions");
                });

            modelBuilder.Entity("Jarvis.Traceability.Api.Models.ProcessResultRecord", b =>
                {
                    b.Navigation("Values");
                });

            modelBuilder.Entity("Jarvis.Traceability.Api.Models.ProcessStep", b =>
                {
                    b.Navigation("Operations");
                });
#pragma warning restore 612, 618
        }
    }
}
